### ISSUE TITLE
Oracle proprietary join: NVL(e.department_id(+), 0) = NVL(d.department_id,0 )

### ISSUE THREAD

**Issue by sqlparser** [sqlparser/sqlfrog#17]
Oracle SQL can't be converted correctly

```sql
SELECT d.department_id, d.department_name, e.employee_id,e.employee_name
FROM   departments d, employees e
WHERE  
NVL(e.department_id(+), 0) = NVL(d.department_id,0 )
ORDER BY d.department_name, e.employee_name;
```

**Comment by cnfree** [comment]
Fixed both of joinConverter and sqlfrog

**Comment by sqlparser** [comment]
It seems the test phase now fails since the latest fix was applied for issue #17:

```

Oracle proprietary join: NVL(e.department_id(+), 0) = NVL(d.department_id,0 ) #17
xxx@yyy:~/sqlfrog-git$ mvn test
[INFO] Scanning for projects...
[WARNING] 
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.gudusoft.sqlfrog.test.datatype.SqlServerDataTypeConvertTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.737 sec
...
Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.087 sec <<< FAILURE!
testOracleJoinToAsni(com.gudusoft.sqlfrog.test.join.OracleJoinConvertTest)  Time elapsed: 0.029 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<... prs.id = nat.prs_id[ AND NULL]
       INNER JOIN o...> but was:<... prs.id = nat.prs_id[]
       INNER JOIN o...>
    at junit.framework.Assert.assertEquals(Assert.java:100)
...
testOracleJoinToAnsi2(com.gudusoft.sqlfrog.test.join.OracleJoinConvertTest)  Time elapsed: 0.018 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<...id = altname.id AND [NULL AND altname.grad_name_ind = '*' AND NULL
       LEFT OUTER JOIN smmtccon.ccn_user ccu
       ON m.id = ccu.id AND NULL]
WHERE  m.id = ?> but was:<...id = altname.id AND [altname.grad_name_ind = '*'
       LEFT OUTER JOIN smmtccon.ccn_user ccu
       ON m.id = ccu.id]
WHERE  m.id = ?>
    at junit.framework.Assert.assertEquals(Assert.java:100)
...
Running com.gudusoft.sqlfrog.test.mix.SqlServerMixConvertTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec
Running com.gudusoft.sqlfrog.test.mix.OracleMixConvertTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec <<< FAILURE!
testOracleMixConvertToMysql(com.gudusoft.sqlfrog.test.mix.OracleMixConvertTest)  Time elapsed: 0.01 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<... `select`.f1 = t2.f1[ AND NULL]
WHERE  `select`.f2 ...> but was:<... `select`.f1 = t2.f1[]
WHERE  `select`.f2 ...>
    at junit.framework.Assert.assertEquals(Assert.java:100)
...
Results :

Failed tests:   testOracleJoinToAsni(com.gudusoft.sqlfrog.test.join.OracleJoinConvertTest): expected:<... prs.id = nat.prs_id[ AND NULL](..)
  testOracleJoinToAnsi2(com.gudusoft.sqlfrog.test.join.OracleJoinConvertTest): expected:<...id = altname.id AND [NULL AND altname.grad_name_ind = '*' AND NULL(..)
  testOracleMixConvertToMysql(com.gudusoft.sqlfrog.test.mix.OracleMixConvertTest): expected:<... `select`.f1 = t2.f1[ AND NULL](..)

Tests run: 26, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by sqlparser** [comment]
this test-case failed as well:

wings/blob/master/java/test/testJoinConverter.java

**Comment by cnfree** [comment]
Fixed it.
